### PR TITLE
Utility functions

### PR DESCRIPTION
**Pull request by Jerry-py**
## Description

Add util functions to Epikcord:

```
sleep_until,
escape_markdown
remove_markdown
escape_mentions
utcnow
```

## Checklist

- [x] - All code changes have been tested, if any
- [ ] - The documentation has been updated accordingly for any code changes
- [ ] - This PR fixes an already existing issue
- [x] - This PR adds a new feature (new functions, methods, classes, parameters, etc.)
- [ ] - This PR fixes a bug
- [ ] - This PR is a breaking change (removes/renames functions, parameters etc.)
- [ ] - This PR is NOT a code change (changes Documentation files, README.md, CONTRIBUTING.md etc.)

## Additional context

The code has been tested because its mostly from the discord.py and I have test `sleep_until`

image

### CODE REVIEW

**Review by nav-github01001 — CHANGES_REQUESTED** [review]
1. Currently everything is held in __init__.py, maybe you can put it in __init__.py until a rewrite happens

**Comment by Jerry-py** [comment]
Alr

**Review by nav-github01001 — APPROVED** [review]
Yeah ,it looks good to me

**Comment by Jerry-py** [comment]
@nav-github01001 Done

**Comment by Jerry-py** [comment]
Waiting for Rid to merge now

**Pull request merged**
