### PR TITLE
Remove iframe tag, add Discord badge

### PR DESCRIPTION
**Pull request by ImNimboss**
Since GitHub flavored markdown doesn't support iframe tags, replace the iframe tag in the README with a Discord server badge from shields.io

### CODE REVIEW

**Review by nav-github01001 — APPROVED** [review]
I think i approve that

**Comment by nav-github01001** [comment]
@TheUntraceable

**Comment by TheUntraceable** [comment]
Haha, love to see people contributing whilst I'm deep asleep! 
image
Nice to see new people contributing, thanks for this, I really didn't have a clue.

**Comment by ImNimboss** [comment]
Haha no problem, I do like some good open source libs I can contribute to :)

**Pull request merged**
