### PR TITLE
Ext features : added not working paginator (needs improvement)

### PR DESCRIPTION
**Pull request by nav-github01001**
## Checklist

- [ ] - All code changes have been tested, if any
- [ ] - The documentation has been updated accordingly for any code changes
- [ ] - This PR fixes an already existing issue
- [x] - This PR adds a new feature (new functions, methods, classes, parameters, etc.)
- [ ] - This PR fixes a bug
- [ ] - This PR is a breaking change (removes/renames functions, parameters etc.)
- [ ] - This PR is NOT a code change (changes Documentation files, README.md, CONTRIBUTING.md etc.)

### CODE REVIEW

**Comment by Jerry-py** [comment]
How about embed.remove_field

**Comment by Jerry-py** [comment]
Or edit

**Comment by Jerry-py** [comment]
Can you fix the bandit checks read it

**Comment by TheUntraceable** [comment]
I might build one from scratch using MessageButtons, I don't think it's that hard tbh. Add a few functions for going left or right or deleting ect.

**Comment by Jerry-py** [comment]
Wow

**Pull request closed without merging**
