### PR TITLE
Inch more closer to production

### PR DESCRIPTION
**Pull request by nav-github01001**
## Description

Just add some few major and minor improvements like implement :class:  StickerItem and improve setup.py

## Checklist

- [ ] - All code changes have been tested, if any
- [ ] - The documentation has been updated accordingly for any code changes
- [ ] - This PR fixes an already existing issue
- [x] - This PR adds a new feature (new functions, methods, classes, parameters, etc.)
- [ ] - This PR fixes a bug
- [x] - This PR is a breaking change (removes/renames functions, parameters etc.)
- [ ] - This PR is NOT a code change (changes Documentation files, README.md, CONTRIBUTING.md etc.)

### CODE REVIEW

**Comment by nav-github01001** [comment]
Note: @TheUntraceable  pls add a [voice] package part before you release the package. I would suggest you do these things

1. please update the README.md because the file will appear in the PyPI page
2. As I said, please add a voice part too

**Review by Jerry-py — APPROVED** [review]
This is better actually

**Review by Jerry-py — COMMENTED** [review]
Why do we raise error when the attribute hasn't been added?

**Review by Jerry-py — APPROVED** [review]
Everything else is good

**Comment by nav-github01001** [comment]
> Why do we raise error when the attribute hasn't been added?

Uhh, It is unhandled exception

**Comment by Jerry-py** [comment]
True

**Comment by nav-github01001** [comment]
@Jerry-py Can you work on #8

**Comment by nav-github01001** [comment]
> True but raises isn't needed let's see what rid has to say @TheUntraceable

It does make it more clearer to the end user

**Comment by Jerry-py** [comment]
I'm not sure how to do that

**Comment by Jerry-py** [comment]
> > True but raises isn't needed let's see what rid has to say @TheUntraceable
> 
> It does make it more clearer to the end user
> 

Ok

**Comment by TheUntraceable** [comment]
> > Why do we raise error when the attribute hasn't been added?
> 
> Uhh, It is unhandled exception

Once I implement `Logger`, I'll switch it to a warning, not an error because there are some events that aren't meant for someone to handle, and they'd be having inefficient code with a single line of code to just have the event registered.

**Comment by TheUntraceable** [comment]
> @Jerry-py Can you work on #8 because I cannot get any opus bin

Take it from Discord.py?

**Pull request merged**
