### PR TITLE
data.get more stuff & fix bugs (tedious)

### PR DESCRIPTION
**Pull request by nav-github01001**
## Description
I have finished adding dict.get(KEY) @TheUntraceable 

## Checklist

- [ ] - All code changes have been tested, if any
- [ ] - The documentation has been updated accordingly for any code changes
- [x] - This PR fixes an already existing issue #43 
- [ ] - This PR adds a new feature (new functions, methods, classes, parameters, etc.)
- [x] - This PR fixes a bug
- [ ] - This PR is a breaking change (removes/renames functions, parameters etc.)
- [ ] - This PR is NOT a code change (changes Documentation files, README.md, CONTRIBUTING.md etc.)

### CODE REVIEW

**Comment by nav-github01001** [comment]
@TheUntraceable

**Comment by nav-github01001** [comment]
kinda fixes #43

**Comment by nav-github01001** [comment]
#44 is also here

**Comment by nav-github01001** [comment]
I hope my efforts are rewarded

Open Source until i die <3

**Comment by Jerry-py** [comment]
Hmm

**Comment by Jerry-py** [comment]
Alot

**Comment by Jerry-py** [comment]
It's good

**Review by TheUntraceable — APPROVED** [review]

**Comment by ImNimboss** [comment]
It's good, but small comment that dict.get is slower than dict[key]. Use it only for values you know are optional

**Pull request merged**
